"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
import secrets
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    default=secrets.token_urlsafe(nbytes=64),
)

IS_HEROKU_APP = "DYNO" in os.environ and "CI" not in os.environ

# The
# SECURITY WARNING: don't run with debug turned on in production!
if not IS_HEROKU_APP:
    DEBUG = True


if IS_HEROKU_APP:
    ALLOWED_HOSTS = ['*']
    # ALLOWED_HOSTS = ["https://the-closet-capsule-1cf6a6c80544.herokuapp.com, https://closet-capsule-frontend-9ae63ded6df2.herokuapp.com"]
else:
    ALLOWED_HOSTS = [".localhost", "127.0.0.1", "[::1]", "0.0.0.0"]



# Application definition

INSTALLED_APPS = [
    "whitenoise.runserver_nostatic",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.closet',
    'apps.ai',
    'apps.notifications',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'djoser',
    'apps.accounts',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Accepts an httpOnly cookie (web, CSRF-enforced) OR an Authorization
        # header (mobile). Subclasses TokenAuthentication, so header auth and the
        # existing tests are unaffected.
        'apps.accounts.authentication.CookieTokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

}

# --- Auth cookie + transport security -------------------------------------
# SECURE is on in production (Heroku) or when DJANGO_SECURE=true. It flips every
# cookie to HTTPS-only and enables HSTS + SSL redirect. Local dev stays plain
# HTTP (SECURE=False) so the Vite proxy can talk to the dev server.
SECURE = IS_HEROKU_APP or os.environ.get("DJANGO_SECURE", "false").lower() == "true"

AUTH_COOKIE_NAME = os.environ.get("AUTH_COOKIE_NAME", "auth_token")
AUTH_COOKIE_MAX_AGE = int(os.environ.get("AUTH_COOKIE_MAX_AGE", str(60 * 60 * 24 * 14)))
AUTH_COOKIE_SAMESITE = os.environ.get("AUTH_COOKIE_SAMESITE", "Lax")
AUTH_COOKIE_SECURE = SECURE

# CSRF cookie must be readable by JS (double-submit); the auth cookie must not.
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = SECURE
SESSION_COOKIE_SECURE = SECURE
SESSION_COOKIE_HTTPONLY = True

# The web client sends credentials (cookies) cross-origin in some deployments.
CORS_ALLOW_CREDENTIALS = True

if SECURE:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", str(60 * 60 * 24 * 365)))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


DJOSER = {
    "USER_ID_FIELD": "username",
    "LOGIN_FIELD": "email",
    # "SEND_ACTIVATION_EMAIL": True,
    # "ACTIVATION_URL": "activate/{uid}/{token}",
    'SERIALIZERS': {
        'token_create': 'apps.accounts.serializers.CustomTokenCreateSerializer',
        'user_create': 'apps.accounts.serializers.UserCreateSerializer',
    },
}

SITE_NAME = "The Closet Project"

# Transactional email is delivered through Resend (see apps/notifications/emails.py).
# When RESEND_API_KEY is unset (local dev, CI) delivery is a logged no-op, so no
# external service is needed to run the app or the tests.
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
RESEND_FROM_EMAIL = os.environ.get(
    "RESEND_FROM_EMAIL", "The Closet Project <onboarding@resend.dev>"
)

# AI chat tuning knobs — env-configurable so they can be tuned per environment
# without a code change (defaults are the v1 values).
#   AI_HISTORY_LIMIT — prior conversation turns sent as context per chat request.
#   AI_RETRIEVE_K    — closet items retrieved (top-K) to ground each reply.
AI_HISTORY_LIMIT = int(os.environ.get("AI_HISTORY_LIMIT", "10"))
AI_RETRIEVE_K = int(os.environ.get("AI_RETRIEVE_K", "5"))
# Recommender retrieves a larger palette than chat so the model has enough items
# to assemble complete outfits from.
AI_RECOMMEND_K = int(os.environ.get("AI_RECOMMEND_K", "20"))

# Logging. Django's default config only wires up its own `django.*` loggers, so
# our `request` middleware logger and `apps.*` module loggers need explicit
# routing to the console or they'd be silent. Level is env-tunable (default INFO);
# root stays at WARNING so third-party libraries don't flood the logs.
LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "%(asctime)s %(levelname)s %(name)s: %(message)s"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
    },
    "root": {"handlers": ["console"], "level": "WARNING"},
    "loggers": {
        # `apps` is the parent of apps.ai.chat, apps.accounts.signals, etc.
        "apps": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
        "request": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
    },
}

# Sentry — error tracking + performance. No-op unless SENTRY_DSN is set (dev/CI),
# so nothing external is required to run the app. The Django + logging integrations
# auto-enable: unhandled exceptions and ERROR-level logs become Sentry events, and
# lower-level logs become breadcrumbs. send_default_pii=False keeps user email/IP
# out of events (privacy); traces_sample_rate defaults to 0 (errors only) and can
# be raised to sample performance transactions incl. DB query spans.
SENTRY_DSN = os.environ.get("SENTRY_DSN", "")
if SENTRY_DSN:
    import sentry_sdk

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.environ.get("SENTRY_ENVIRONMENT", "development"),
        traces_sample_rate=float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE", "0.0")),
        send_default_pii=False,
    )

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    # One log line per request; high in the stack so it times the whole request.
    'backend.middleware.RequestLoggingMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOWED_ORIGINS = [
        "http://127.0.0.1:3000",
    "http://127.0.0.1",
    "http://localhost:3000",
    "http://localhost",
    "http://127.0.0.1:3001",
    "http://localhost:3001",
    "https://closet-capsule-frontend-9ae63ded6df2.herokuapp.com",
    "https://the-closet-capsule-1cf6a6c80544.herokuapp.com"
]

# Django checks the request Origin against this list for state-changing (POST/
# PATCH/DELETE) requests. The dev frontend runs at localhost:3000 and proxies to
# the backend, so the browser's Origin is http://localhost:3000 — it must be
# trusted here or every write fails "Origin checking failed". Mirrors the local
# entries in CORS_ALLOWED_ORIGINS.
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "https://closet-capsule-frontend-9ae63ded6df2.herokuapp.com",
    "https://the-closet-capsule-1cf6a6c80544.herokuapp.com",
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# Use DATABASE_URL whenever it is set (Docker/pgvector locally, and Fly/Render/Heroku
# in prod); fall back to SQLite only for running manage.py natively with no Docker.
# dj-database-url parses the URL string into Django's DATABASES dict.
if os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(
            env="DATABASE_URL",
            conn_max_age=600,           # reuse DB connections for 10 min (perf)
            conn_health_checks=True,    # verify a reused connection is still alive
            ssl_require=IS_HEROKU_APP,  # require SSL only in managed prod; local Postgres has none
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STORAGES = {
    # Uploaded media (ImageField/FileField) — local filesystem under MEDIA_ROOT.
    # Overriding STORAGES replaces Django's defaults wholesale, so "default" must
    # be declared explicitly or file saves fail with "no config for 'default'".
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # Enable WhiteNoise's GZip and Brotli compression of static assets:
    # https://whitenoise.readthedocs.io/en/latest/django.html#add-compression-and-caching-support
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Don't store the original (un-hashed filename) version of static files, to reduce slug size:
# https://whitenoise.readthedocs.io/en/latest/django.html#WHITENOISE_KEEP_ONLY_HASHED_FILES
WHITENOISE_KEEP_ONLY_HASHED_FILES = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
