# Generated by Django 4.1.4 on 2022-12-25 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='worn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='worn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
