# Generated by Django 4.1 on 2023-08-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_clothingtype_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='cover',
            new_name='cover_file',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='cover_url',
            field=models.URLField(default='DEFAULT'),
            preserve_default=False,
        ),
    ]
