# Generated by Django 5.2.16 on 2026-07-23 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_photo', models.ImageField(blank=True, null=True, upload_to='body/')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('email_recommendations', models.BooleanField(default=True)),
                ('email_updates', models.BooleanField(default=True)),
                ('sms_opt_in', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
