# Generated by Django 5.2.16 on 2026-07-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_email_not_blank_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="remove_background",
            field=models.BooleanField(default=True),
        ),
    ]
