# Generated by Django 5.2.16 on 2026-07-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_remove_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
