# Generated by Django 4.1.4 on 2022-12-27 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('closet', '0002_alter_clothingitem_worn_alter_outfit_worn'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingtype',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
