# Generated by Django 4.1 on 2023-08-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0004_rename_cover_clothingitem_cover_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='cover_url',
        ),
    ]
