# Generated by Django 5.2.16 on 2026-07-24 02:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0007_clothingitem_price_outfit_base_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='worn',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='worn',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
